env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  SONAR_HOST: "https://sonarcloud.io"
steps:
  - group: ":test_tube: Tests"
    key: "tests"
    depends_on: "precheck"
    steps:
    - label: ":golangci-lint: lint :lint-roller:"
      key: "lint"
      plugins:
        - docker#v5.11.0:
            image: "registry.hub.docker.com/golangci/golangci-lint:v1.58.1"
            command: ["golangci-lint", "run", "-v", "--timeout", "10m"]
            environment: 
              - "GOTOOLCHAIN=auto"
  - label: ":github: upload PR reports"
    key: "scan-upload-pr"
    if: build.pull_request.id != null
    depends_on: ["gosec", "go_test_libsql"]
    plugins:
      - artifacts#v1.9.3:
          download: "results.txt"
      - docker#v5.11.0:
            image: "sonarsource/sonar-scanner-cli:5"
            environment:
              - "SONAR_TOKEN"
              - "SONAR_HOST_URL=$SONAR_HOST"
              - "SONAR_SCANNER_OPTS=-Dsonar.pullrequest.branch=$BUILDKITE_BRANCH -Dsonar.pullrequest.base=$BUILDKITE_PULL_REQUEST_BASE_BRANCH -Dsonar.pullrequest.key=$BUILDKITE_PULL_REQUEST"